### ISSUE TITLE
[BUG] Unable to decrypt Messages

### ISSUE THREAD

**Issue by wednesday-256** [Keeper-Wallet/Keeper-Wallet-Extension#1049]
**Describe the bug**
Unable to decrypt messages using a test account and public key from KeeperWallet.publicState().account.publicKey get {message:'invalid key'} instead

**To Reproduce**
Open console
Type KeeperWallet.decryptMessage('**encryptedMessage**', "*publicKEY*", "*encoding phrase*").then(console.log)

**Expected behavior**
I expected to get a response  with decrypted message instead i keep getting the error response {message: "invalid key"}

**Screenshots**

**Environment**
Please complete the following information.

- Version of ProviderKeeper: 2.13.7
- OS: Windows
- Browser version: Chromium Version 108.0.5357.0 (Developer Build) (64-bit)

**Additional context**
Not sure if this makes a difference, but I was using a Testnet account and was running the app from localhost.

**Comment by msmolyakov** [comment]
Hey, @wednesday-256, thank you for the report!

We've fixed it recently:
#1021
#1038 

The fix will be published in the next few days. I will let you know.

**Comment by wednesday-256** [comment]
Oooh thank you very much for this, I really appreciate the work you put in and how intuitive it is.

**Comment by msmolyakov** [comment]
We published v2.13.9 with the fix today. Please try it

**Comment by wednesday-256** [comment]
Yes, I just checked, and it works; thank you so much for your reply and work on this extension, it simplifies the interaction with the waves blockchain and makes prototyping functionalities with different applications easy and intuitive.
